### ISSUE TITLE
Error: geterr timeout

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/typescript-language-server#82]
Unfortunately, I do not know how to reproduce. I got this in my Theia backend console:
```
root ERROR TypeScript: (node:61133) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

root ERROR TypeScript: (node:61133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:61133) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

root ERROR TypeScript: (node:61133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:61133) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:61133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by felixfbecker** [comment]
I get this a lot when running `yarn` while the server is running. After the installation is done, doing some requests like `definition`, logs start to appear like
```
Language server: (node:64993) UnhandledPromiseRejectionWarning: Error: geterr timeout    at Timeout.Deferred.timer.setTimeout (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript-language-server/lib/utils.js:24:25)    at listOnTimeout (timers.js:324:15)    at processTimers (timers.js:268:5)(node:64993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by domq** [comment]
Observing this too with Emacs and [`lsp-mode`](https://github.com/emacs-lsp/lsp-mode)

**Comment by domq** [comment]
Here is a workaround in Emacs (version > 24.4) that forces typescript-language-server to restart as soon as it hits this issue (instead of falling into a catatonic state and pulling down Emacs' IDE functionality into it as well):

```elisp
(require 'cl)
(with-eval-after-load 'lsp-clients
    (cl-nsubst '(nconc (list "/usr/local/bin/node" "--unhandled-rejections=strict" (lsp-package-path 'typescript-language-server)) (cons "--tsserver-path" (cons (lsp-package-path 'typescript) lsp-clients-typescript-server-args)))
               '(cons (lsp-package-path 'typescript-language-server) (cons "--tsserver-path" (cons (lsp-package-path 'typescript) lsp-clients-typescript-server-args)))
               (lsp--client-new-connection (gethash 'ts-ls lsp-clients))
               :test 'equal))
```

**Comment by dvcrn** [comment]
Ran into this today as well with a bigger project. Only on that one project though, other ones are working fine...

**Comment by skrat** [comment]
I'm having the same issue since recently, in a project that used to work fine. I update my system regularly (arch) so I guess it's a new thing again? I can't get it to work, the error won't say what exactly timed out.

**Comment by shackra** [comment]
I'm having troubles with this as well:

```
/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24
            this.reject(new Error(this.operation + " timeout"));
                        ^

Error: geterr timeout
    at Timeout.<anonymous> (/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24:25)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

Process ts-ls stderr finished
/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24
            this.reject(new Error(this.operation + " timeout"));
                        ^

Error: geterr timeout
    at Timeout.<anonymous> (/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24:25)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

Process ts-ls stderr finished
/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24
            this.reject(new Error(this.operation + " timeout"));
                        ^

Error: geterr timeout
    at Timeout.<anonymous> (/home/jorge/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24:25)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

Process ts-ls stderr finished
```

**Comment by shackra** [comment]
I updated this package and also typescript to the latest release and even my bug at #175 is gone

**Comment by shackra** [comment]
> I updated this package and also typescript to the latest release and even my bug at #175 is gone

was wrong, I still experience this #82

**Comment by nickhstr** [comment]
I'm consistently experiencing this issue as well, whenever the language server starts, for one particularly large project.
My workaround is to increase the timeout in `typescript-language-server/lib/utils.js`, from the current value of `20000`.

I'm pretty unfamiliar with the server's source, but is it possible to make this timeout value configurable? And possibly default to a minute instead of 20 seconds?

**Comment by shackra** [comment]
> I'm consistently experiencing this issue as well, whenever the language server starts, for one particularly large project.
> My workaround is to increase the timeout in `typescript-language-server/lib/utils.js`, from the current value of `20000`.
> 
> I'm pretty unfamiliar with the server's source, but is it possible to make this timeout value configurable? And possibly default to a minute instead of 20 seconds?

how do you achieve that when managing the global installation with `yarn`? with [patch-package](https://www.npmjs.com/package/patch-package)?

**Comment by DonnieWest** [comment]
On the timeout, I'm definitely open to PRs configuring that timeout. I'm additionally happy to help someone get started if they want to get that rolling

I'll mention that it'd be nice (but not necessary) to move away from command line flags and to a more idiomatic way of configuring the server too

**Comment by apexskier** [comment]
Is this resolved by https://github.com/theia-ide/typescript-language-server/pull/189?

**Comment by rchl** [comment]
I'd say so. Some people have somewhat similar issue still but there is #82 issue for that.

**Comment by shackra** [comment]
```
/home/jorge/node_modules/typescript-language-server/lib/utils.js:24
            this.reject(new Error(this.operation + " timeout"));
                        ^

Error: geterr timeout
    at Timeout.<anonymous> (/home/jorge/node_modules/typescript-language-server/lib/utils.js:24:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

Process ts-ls stderr finished
```

I still get this annoying error message

`typescript-language-server --version` prints `0.6.4`

**Comment by rchl** [comment]
@shackra this code doesn't exist in the server since version 0.5.2 so you are definitively not running 0.6.4 if that happens.

**Comment by shackra** [comment]
I see, thanks for the tipo @rchl
